# Generated by Django 2.1 on 2018-09-08 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('ticker', models.CharField(max_length=10)),
                ('current_liab', models.BigIntegerField()),
                ('equity', models.BigIntegerField()),
                ('total_assets', models.BigIntegerField()),
                ('revenue12', models.BigIntegerField()),
                ('revenue13', models.BigIntegerField()),
                ('revenue14', models.BigIntegerField()),
                ('revenue15', models.BigIntegerField()),
                ('revenue16', models.BigIntegerField()),
                ('ebit', models.BigIntegerField()),
                ('netincome12', models.BigIntegerField()),
                ('netincome13', models.BigIntegerField()),
                ('netincome14', models.BigIntegerField()),
                ('netincome15', models.BigIntegerField()),
                ('netincome16', models.BigIntegerField()),
                ('free_cashflow', models.BigIntegerField()),
                ('eps12', models.DecimalField(decimal_places=2, max_digits=8)),
                ('eps13', models.DecimalField(decimal_places=2, max_digits=8)),
                ('eps14', models.DecimalField(decimal_places=2, max_digits=8)),
                ('eps15', models.DecimalField(decimal_places=2, max_digits=8)),
                ('eps16', models.DecimalField(decimal_places=2, max_digits=8)),
                ('eps_e', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total_dividend', models.BigIntegerField()),
                ('dividend_ps', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
